import type { Preset } from './types'

/** Maximum saturation, tilted camera, heaviest scroll smear of the set. */
export const riot: Preset = {
  engine: 'particles',
  key: 'riot',
  label: 'Riot — festival',
  brand: 'Riot',
  tagline: 'Three days, no sleep',
  figure: 'speaker',
  mood: {
    roughness: 0.34, metalness: 0.3, envIntensity: 1.1,
    tint: 0.6, fresnel: 0.3, fresnelVelocity: 2.2, fresnelPower: 2.2,
    bloomIntensity: 0.7, bloomThreshold: 0.88, grain: 0.16, vignette: 0.26, aberration: 2.4,
    damping: 0.78, tilt: 0.07, distance: 6.2,
    ambient: 1.1, key: 2.6, rim: 70,
    debris: { count: 8, scale: 1.05, kinds: ['icosa', 'torus', 'box', 'capsule'] },
    figurePosition: [2.45, -0.15, -2.3], figureScale: 1,
  },
  sections: [
    { id: 'hero', word: 'LOUD', bg: '#12061c', fg: '#ffd400', word3d: '#ff2e88', accent: '#7cffcb',
      kicker: '14–16 Aug / One field / Somerset', title: 'Three days. No sleep. One field.',
      body: 'Sixty acres, four stages, and a sound system loud enough that the village two miles over files a complaint every single year.' },
    { id: 'bass', word: 'BASS', bg: '#ff2e88', fg: '#12061c', word3d: '#ffd400', accent: '#7cffcb',
      kicker: '01 — The sound', title: 'You will feel it in your sternum.',
      body: 'A hundred and twelve kilowatts across four stacks, tuned on site the morning of. The low end is not an effect, it is the point.',
      facts: [['112', 'kilowatts'], ['4', 'stages'], ['28Hz', 'floor']] },
    { id: 'riot', word: 'RIOT', bg: '#ffd400', fg: '#12061c', word3d: '#ff2e88', accent: '#12061c',
      kicker: '02 — The line-up', title: 'Ninety acts. Half of them you have not heard of yet.',
      body: 'We book the second stage before the headliners. That is where the ones you will be talking about next year are playing at 4pm on a Friday.',
      facts: [['90', 'acts'], ['62%', 'first-timers'], ['0', 'clashes']] },
    { id: 'late', word: 'LATE', bg: '#12061c', fg: '#7cffcb', word3d: '#7cffcb', accent: '#ff2e88',
      kicker: '03 — After dark', title: 'The good part starts at two.',
      body: 'Two woodland stages that do not appear on any map, running until the sun comes up. Find them the way everyone else does.',
      facts: [['2am', 'second wind'], ['2', 'hidden stages'], ['06:04', 'sunrise']] },
    { id: 'one', word: 'ONE', bg: '#ff2e88', fg: '#ffd400', word3d: '#ffd400', accent: '#7cffcb',
      kicker: '04 — Tickets', title: 'One price. Everything included.',
      body: 'Camping, parking, water, and every stage. No tiers, no VIP, no queue-jump you can buy. It sells out in April.' },
  ],
}
